version = 3.10.5
runner.dialect = scala3
runner.dialectOverride.withAllowToplevelTerms = true
runner.dialectOverride.withAllowEndMarker = false
runner.dialectOverride.allowSignificantIndentation = false

//align.preset=more
align.arrowEnumeratorGenerator = true
align.tokens = [
  {
    code = "%"
    owners = [{
      regex = "Term.ApplyInfix"
    }]
  }, {
    code = "%%"
    owners = [{
      regex = "Term.ApplyInfix"
    }]
    //  }, {
    //    code = ":="
    //    owners = [{
    //      regex = "Term.ApplyInfix",
    //    }]
  }, {
    code = "->"
    owners = [{
      regex = "Term.ApplyInfix",
    }]
  }, {
    code = "="
    owners = [{
      regex = "(Enumerator.Val|Defn.(Va(l|r)|GivenAlias|Def|Type))"
    }]
  }, {
    code = "<-"
    owners = [{
      regex = "Enumerator.Generator"
    }]
  },
]

maxColumn=140
assumeStandardLibraryStripMargin=false

indent.caseSite = 5

continuationIndent.callSite=2
continuationIndent.defnSite=2

align.stripMargin=true
align.multiline=true
align.openParenCallSite=false
align.openParenDefnSite=false

newlines.selectChains.classicCanStartWithBraceApply = true
newlines.selectChains.classicCanStartWithoutApply = true

newlines.selectChains.classicKeepFirst = true
docstrings.forceBlankLineBefore = true

spaces.beforeContextBoundColon=Never
spaces.inImportCurlyBraces=false

//newlines.beforeMultiline=unfold
newlines.beforeMultilineDef=keep
newlines.alwaysBeforeElseAfterCurlyIf=false
newlines.beforeCurlyLambdaParams=multilineWithCaseOnly
newlines.afterCurlyLambdaParams=never
newlines.implicitParamListModifierPrefer = before

trailingCommas=multiple

docstrings.style = SpaceAsterisk
docstrings.oneline = keep
docstrings.wrap = false

rewrite {
  rules = [
    SortImports
    AvoidInfix
    PreferCurlyFors
    SortModifiers
  ]
}

