comment:
  layout: "reach, diff, flags, files"
  behavior: default
ignore:
  - "modules/refined4s-core/shared/src/main/scala/refined4s/internal/numericTools.scala"
  - "modules/refined4s-core/shared/src/main/scala/refined4s/internal/NumericValidator.scala"
  - "modules/refined4s-refined-compat-scala2/shared/src/main/scala-2/refined4s/compat/RefinedTypesCompat.scala"
